version: '3.8'

services:
  backend:
    build:
      target: development
    volumes:
      - ./apps/backend:/app
      - /app/.venv
    environment:
      DEBUG: "true"
      RELOAD: "true"
    command: uv run fastapi dev app/main.py --host 0.0.0.0 --reload

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: development
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./packages/domain:/app/packages/domain
      - ./packages/shared:/app/packages/shared
      - ./packages/ui:/app/packages/ui
      - ./scripts:/app/scripts:ro
    environment:
      NODE_ENV: development
    command: pnpm dev

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres