"""Add task mode resource requirements table

Revision ID: 5b8f9e1d2c3a
Revises: 1a31ce608336
Create Date: 2025-08-08 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b8f9e1d2c3a'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create task_modes table
    op.create_table('task_modes',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('mode_name', sa.VARCHAR(length=100), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('cost_per_minute', sa.Float(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_modes_task_id'), 'task_modes', ['task_id'], unique=False)

    # Create task_mode_resource_requirements table
    op.create_table('task_mode_resource_requirements',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('mode_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('skill_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('quantity_required', sa.Integer(), nullable=False),
        sa.Column('skill_level', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', name='skilllevel'), nullable=False),
        sa.Column('is_partial_consumption', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['mode_id'], ['task_modes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['skill_id'], ['skill_types.id'], ),
        sa.PrimaryKeyConstraint('mode_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_mode_resource_requirements')
    op.drop_index(op.f('ix_task_modes_task_id'), table_name='task_modes')
    op.drop_table('task_modes')
    # ### end Alembic commands ###