"""add_task_templates_table

Revision ID: f1a2b3c4d5e6
Revises: d98dd8ec85a3
Create Date: 2025-01-08 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'd98dd8ec85a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('task_id', sa.String(), nullable=False),
        sa.Column('sequence_id', sa.String(), nullable=True),
        sa.Column('department_id', sa.String(length=10), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('is_unattended', sa.Boolean(), nullable=False),
        sa.Column('is_setup', sa.Boolean(), nullable=False),
        sa.Column('wip_limit', sa.Integer(), nullable=False),
        sa.Column('max_batch_size', sa.Integer(), nullable=False),
        sa.Column('setup_for_task_id', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_templates_department', 'task_templates', ['department_id'], unique=False)
    op.create_index('idx_task_templates_sequence', 'task_templates', ['sequence_id'], unique=False)
    op.create_index('idx_task_templates_setup_for', 'task_templates', ['setup_for_task_id'], unique=False)
    op.create_index('idx_task_templates_task_id', 'task_templates', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_templates_task_id', table_name='task_templates')
    op.drop_index('idx_task_templates_setup_for', table_name='task_templates')
    op.drop_index('idx_task_templates_sequence', table_name='task_templates')
    op.drop_index('idx_task_templates_department', table_name='task_templates')
    op.drop_table('task_templates')
    # ### end Alembic commands ###